apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: virtbmc-sa
    app.kubernetes.io/component: virtbmc-rbac
    app.kubernetes.io/created-by: kubevirtbmc
    app.kubernetes.io/part-of: kubevirtbmc
    app.kubernetes.io/managed-by: kustomize
  name: virtbmc
  namespace: system
