---
apiVersion: v2
name: kubevirtbmc
version: 0.0.0-dev
description: A Helm chart for KubeVirtBMC
type: application
keywords:
- kubernetes
- kubevirt
- ipmi
- redfish
home: https://github.com/starbops/kubevirtbmc
sources:
- https://github.com/starbops/kubevirtbmc
maintainers:
- name: starbops
  email: starbops@hey.com
  url: https://www.zespre.com
appVersion: main-head
