version: "2"
run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - unused
    # disabled: dupl, ginkgolinter, lll, revive, staticcheck
  disable:
    - dupl
    - ginkgolinter
    - lll
    - revive
    - staticcheck

  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing

  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
