# permissions for end users to edit virtualmachinebmcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualmachinebmc-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: virtualmachinebmc
    app.kubernetes.io/part-of: virtualmachinebmc
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachinebmc-editor-role
rules:
- apiGroups:
  - virtualmachine.kubevirt.org
  resources:
  - virtualmachinebmcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virtualmachine.kubevirt.org
  resources:
  - virtualmachinebmcs/status
  verbs:
  - get
