apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificate
    app.kubernetes.io/part-of: kubevirtbmc
  name: {{ include "chart.name" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificate
    app.kubernetes.io/part-of: kubevirtbmc
  name: {{ include "chart.name" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ include "chart.name" . }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ include "chart.name" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "chart.name" . }}-selfsigned-issuer
  secretName: {{ include "chart.name" . }}-webhook-server-cert
