apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virt-bmc-role
    app.kubernetes.io/component: virt-bmc-rbac
    app.kubernetes.io/created-by: kubevirtbmc
    app.kubernetes.io/part-of: kubevirtbmc
    app.kubernetes.io/managed-by: kustomize
  name: virt-bmc-role
rules:
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  verbs:
  - get
  - list
  - watch
  - delete
