apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kbmc-role
    app.kubernetes.io/component: kbmc-rbac
    app.kubernetes.io/created-by: virtualmachinebmc
    app.kubernetes.io/part-of: virtualmachinebmc
    app.kubernetes.io/managed-by: kustomize
  name: kbmc-role
rules:
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  verbs:
  - get
  - list
  - watch
  - delete
