apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: kbmc-rolebinding
    app.kubernetes.io/component: kbmc-rbac
    app.kubernetes.io/created-by: virtualmachinebmc
    app.kubernetes.io/part-of: virtualmachinebmc
    app.kubernetes.io/managed-by: kustomize
  name: kbmc-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kbmc-role
subjects:
- kind: ServiceAccount
  name: kbmc
  namespace: system
