apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: kbmc-sa
    app.kubernetes.io/component: kbmc-rbac
    app.kubernetes.io/created-by: virtualmachinebmc
    app.kubernetes.io/part-of: virtualmachinebmc
    app.kubernetes.io/managed-by: kustomize
  name: kbmc
  namespace: system
