name: Pull Request Build

on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
            starbops/kubebmc-controller
            starbops/kbmc
    - name: Test
      run: make test
    - name: Build
      run: make build
    - name: Docker build (controller)
      uses: docker/build-push-action@v6
      with:
        provenance: false
        context: .
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Docker build (kbmc)
      uses: docker/build-push-action@v6
      with:
        provenance: false
        context: .
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile.kbmc
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
