name: Tag Build and Publish

on:
  push:
    tags:
    - "v*"

jobs:
  build-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - dockerfile: ./Dockerfile
          image: starbops/kubebmc-controller
        - dockerfile: ./Dockerfile.kbmc
          image: starbops/kbmc
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ matrix.image }}
    - name: Docker build and push
      uses: docker/build-push-action@v6
      with:
        provenance: false
        context: .
        platforms: linux/amd64,linux/arm64
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
