name: Tag Build and Publish

on:
  push:
    tags:
    - "v*"

jobs:
  build-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      REPO: starbops
      MANAGER: virtbmc-controller
      AGENT: virtbmc
      VERSION: ${{ github.ref_name }}
      GIT_COMMIT: ${{ github.sha }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ matrix.image }}
    - name: Docker build and push manager
      uses: docker/build-push-action@v6
      with:
        provenance: false
        context: .
        build-args: |
          LINKFLAGS=-X main.AppVersion=${{ env.VERSION }} -X main.GitCommit=${{ env.GIT_COMMIT }}
        platforms: linux/amd64,linux/arm64
        file: Dockerfile
        push: true
        tags: ${{ env.REPO }}/${{ env.MANAGER }}:${{ env.VERSION }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Docker build and push agent
      uses: docker/build-push-action@v6
      with:
        provenance: false
        context: .
        build-args: |
          LINKFLAGS=-X main.AppVersion=${{ env.VERSION }} -X main.GitCommit=${{ env.GIT_COMMIT }}
        platforms: linux/amd64,linux/arm64
        file: Dockerfile.virtbmc
        push: true
        tags: ${{ env.REPO }}/${{ env.AGENT }}:${{ env.VERSION }}
        labels: ${{ steps.meta.outputs.labels }}
